# Generated by Django 4.2.3 on 2023-07-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='titre',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
