# Generated by Django 4.2.3 on 2023-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_alter_film_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
