# Generated by Django 3.2.2 on 2023-07-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_film_id'),
        ('acteur', '0004_alter_actor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='film',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='film.film'),
        ),
    ]
