# Generated by Django 4.2.3 on 2023-07-25 11:11

from django.db import migrations, models
import django.db.models.deletion
import review.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0005_alter_film_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.PositiveIntegerField(validators=[review.validation.validate_grade])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='film.film')),
            ],
        ),
    ]
